# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "autotest-tmux"
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["MIKAMI Yoshiyuki"]
  s.date = "2013-04-21"
  s.description = "displays autotest/autospec progress on tmux status-right."
  s.email = "yoshuki@saikyoline.jp"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "autotest-tmux.gemspec",
    "autotest/discover.rb",
    "lib/autotest/tmux.rb",
    "spec/autotest-tmux_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/yoshuki/autotest-tmux"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "displays autotest/autospec progress on tmux status-right."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<autotest>, [">= 4.4.1"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<autotest>, [">= 4.4.1"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_runtime_dependency(%q<autotest>, [">= 0"])
    else
      s.add_dependency(%q<autotest>, [">= 4.4.1"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<autotest>, [">= 4.4.1"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<autotest>, [">= 0"])
    end
  else
    s.add_dependency(%q<autotest>, [">= 4.4.1"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<autotest>, [">= 4.4.1"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<autotest>, [">= 0"])
  end
end

